name: Build and Upload Artifact

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        check-latest: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  # Adjust the Node.js version as per your requirement

    - name: Clone Repo and Build
      run: |
        git clone https://github.com/ymyuuu/memos
        cd memos
        corepack enable && pnpm i --frozen-lockfile
        pnpm build
        GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o memos ./bin/memos/main.go && rm -f artifact/* && cp memos artifact/memos.exe && cd artifact && tar -czvf ../memos-windows-amd64.tar.gz * && cd ..
        GOOS=freebsd GOARCH=amd64 CGO_ENABLED=0 go build -o memos ./bin/memos/main.go && rm -f artifact/* && cp memos artifact/memos && cd artifact && tar -czvf ../memos-freebsd-amd64.tar.gz * && cd ..
        GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o memos ./bin/memos/main.go && rm -f artifact/* && cp memos artifact/memos && cd artifact && tar -czvf ../memos-darwin-amd64.tar.gz * && cd ..
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o memos ./bin/memos/main.go && rm -f artifact/* && cp memos artifact/memos && cd artifact && tar -czvf ../memos-linux-amd64.tar.gz * && cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: memos-pre-built
        path: |
            memos/artifact/memos-windows-amd64.tar.gz
            memos/artifact/memos-freebsd-amd64.tar.gz
            memos/artifact/memos-darwin-amd64.tar.gz
            memos/artifact/memos-linux-amd64.tar.gz
