name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        check-latest: true

    - name: Clone Repo and Build
      run: |
        git clone https://github.com/ymyuuu/memos
        cd memos
        GOOS=freebsd GOARCH=amd64 CGO_ENABLED=0 go build -o memos ./bin/memos/main.go
        mkdir -p artifact
        cp memos artifact/memos-freebsd-amd64
        cd artifact
        tar -czvf ../memos-freebsd-amd64.tar.gz *
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: memos-pre-built
        path: memos/memos-freebsd-amd64.tar.gz

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8
