name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        check-latest: true

    - name: Clone Repo
      run: |
        export LATEST_APP=$(wget -qO- https://api.github.com/repos/ymyuuu/memos/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
        git clone -b $LATEST_APP https://github.com/ymyuuu/memos
        npm install -g pnpm

    - name: Build binary
      run: |
        cd memos
        GOOS=freebsd GOARCH=amd64 CGO_ENABLED=0 go build -o memos ./bin/memos/main.go && rm -f artifact/* && cp memos artifact/memos && cd artifact && tar -czvf ../memos-freebsd-amd64.tar.gz * && cd ..
        cd ..
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: memos-pre-built
        path: memos/memos-freebsd-amd64.tar.gz
            
    - name: Generate release tag
      id: tag
      run: echo "release_tag=$(wget -qO- https://api.github.com/repos/ymyuuu/memos/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')" >> $GITHUB_ENV

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: memos/memos-freebsd-amd64.tar.gz

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8
